//Maya Preference 2026 (Release 1)
//
//

runTimeCommand
	-label ""
	-annotation "Flow Wedging job submit notification before graph export"
	-longAnnotation ""
	-category "FlowWedging.Flow Wedging Job"
	-image ""
	-tags ""
	-keywords ""
	-plugin ""
	-helpUrl ""
	-hotkeyCtx ""
	-commandLanguage "mel"
	-command ("print(\"# Flow Wedging Job submission starting...\\n\")")
	FlowWedgingSubmitJob;

runTimeCommand
	-label ""
	-annotation "Flow Wedging job failed to submit to farm"
	-longAnnotation ""
	-category "FlowWedging.Flow Wedging Job"
	-image ""
	-tags ""
	-keywords ""
	-plugin ""
	-helpUrl ""
	-hotkeyCtx ""
	-commandLanguage "mel"
	-command ("print(\"# Flow Wedging Job failed to submit\\n\")")
	FlowWedgingSubmitJobFailed;

runTimeCommand
	-label ""
	-annotation "Flow Wedging Job submitted to farm successfully"
	-longAnnotation ""
	-category "FlowWedging.Flow Wedging Job"
	-image ""
	-tags ""
	-keywords ""
	-plugin ""
	-helpUrl ""
	-hotkeyCtx ""
	-commandLanguage "mel"
	-command ("print(\"# Flow Wedging Job submitted successfully\\n\")")
	FlowWedgingSubmitJobSucceeded;

runTimeCommand
	-label ""
	-annotation "Flow Wedging Job submitted with wedges to farm successfully"
	-longAnnotation ""
	-category "FlowWedging.Flow Wedging Job"
	-image ""
	-tags ""
	-keywords ""
	-plugin ""
	-helpUrl ""
	-hotkeyCtx ""
	-commandLanguage "mel"
	-command ("print(\"# Flow Wedging Job submitted successfully with wedges\\n\")")
	FlowWedgingSubmitJobSucceededWithWedging;

runTimeCommand
	-label ""
	-annotation "Flow Wedging Job submitted with render preview"
	-longAnnotation ""
	-category "FlowWedging.Flow Wedging Job"
	-image ""
	-tags ""
	-keywords ""
	-plugin ""
	-helpUrl ""
	-hotkeyCtx ""
	-commandLanguage "mel"
	-command ("print(\"# Flow Wedging Job submitted successfully with render preview\\n\")")
	FlowWedgingSubmitJobSucceededWithRenderPreview;

runTimeCommand
	-label ""
	-annotation "Flow Wedging monthly scratch storage limit has been reached"
	-longAnnotation ""
	-category "FlowWedging.Flow Wedging Job"
	-image ""
	-tags ""
	-keywords ""
	-plugin ""
	-helpUrl ""
	-hotkeyCtx ""
	-commandLanguage "mel"
	-command ("print(\"# Flow Wedging monthly scratch storage limit has been reached\\n\")")
	FlowWedgingMonthlyScratchStorageLimitReached;

runTimeCommand
	-label ""
	-annotation "Flow Retopo job submitted notification"
	-longAnnotation ""
	-category "FlowRetopo.Flow Retopo"
	-image ""
	-tags ""
	-keywords ""
	-plugin ""
	-helpUrl ""
	-hotkeyCtx ""
	-commandLanguage "mel"
	-command ("print(\"# Starting Flow Retopology Job Submission...\\n\")")
	FlowRetopoSubmitJob;

runTimeCommand
	-label ""
	-annotation "Flow Retopo job completed successfully"
	-longAnnotation ""
	-category "FlowRetopo.Flow Retopo Job"
	-image ""
	-tags ""
	-keywords ""
	-plugin ""
	-helpUrl ""
	-hotkeyCtx ""
	-commandLanguage "mel"
	-command ("print(\"# Flow Retopology Job completed successfully\\n\")")
	FlowRetopoJobSuccess;

runTimeCommand
	-label ""
	-annotation "Flow Retopo job did not complete successfully"
	-longAnnotation ""
	-category "FlowRetopo.Flow Retopo Job"
	-image ""
	-tags ""
	-keywords ""
	-plugin ""
	-helpUrl ""
	-hotkeyCtx ""
	-commandLanguage "mel"
	-command ("print(\"# Flow Retopology Job did not complete successfully\\n\")")
	FlowRetopoJobFailure;

runTimeCommand
	-label ""
	-annotation "Flow Retopo job was canceled"
	-longAnnotation ""
	-category "FlowRetopo.Flow Retopo Job"
	-image ""
	-tags ""
	-keywords ""
	-plugin ""
	-helpUrl ""
	-hotkeyCtx ""
	-commandLanguage "mel"
	-command ("print(\"# Flow Retopology Job was canceled\\n\")")
	FlowRetopoJobCanceled;

runTimeCommand
	-label ""
	-annotation "Flow Retopology monthly job submission limit has been reached"
	-longAnnotation ""
	-category "FlowRetopo.Flow Retopo Job"
	-image ""
	-tags ""
	-keywords ""
	-plugin ""
	-helpUrl ""
	-hotkeyCtx ""
	-commandLanguage "mel"
	-command ("print(\"# Flow Retopology monthly job submission limit has been reached\\n\")")
	FlowRetopoMonthlySubmissionLimitReached;

runTimeCommand
	-label ""
	-annotation "Flow Retopology monthly scratch space limit has been reached"
	-longAnnotation ""
	-category "FlowRetopo.Flow Retopo Job"
	-image ""
	-tags ""
	-keywords ""
	-plugin ""
	-helpUrl ""
	-hotkeyCtx ""
	-commandLanguage "mel"
	-command ("print(\"# Flow Retopology monthly scratch space limit has been reached\\n\")")
	FlowRetopoMonthlyScratchStorageLimitReached;

